CONST_DEFAULT_CONFIGS = [
    ('NewHostsDetection', 0),
    ('LocalFlowsDetection', 0),
    ('RouterFlowsDetection', 0),
    ('ForeignFlowsDetection', 0),
    ('NewOutboundDetection', 0),
    ('GeolocationFlowsDetection', 0),
    ('BypassLocalDnsDetection', 0),
    ('IncorrectAuthoritativeDnsDetection', 0),
    ('BypassLocalNtpDetection', 0),
    ('IncorrectNtpStratrumDetection', 0),
    ('ApprovedLocalNtpServersList',''),
    ('ApprovedLocalDnsServersList',''),
    ('ApprovedAuthoritativeDnsServersList',''),
    ('ApprovedNtpStratumServersList',''),
    ('BannedCountryList','China,North Korea,Iran,Russia,Ukraine,Georgia,Armenia,Azerbaijan,Belarus,Syria,Venezuela,Cuba,Myanmar,Afghanistan'),
    ('LocalNetworks',''),
    ('RouterIpAddresses',''),
    ('ProcessingInterval','60'),
    ('TelegramBotToken',''),
    ('TelegramChatId',''),
    ('ScheduleProcessor','0'),
    ('StartCollector','1'),
    ('CleanNewFlows','0'),
    ('DeadConnectionDetection','0'),
    ('IgnoreListEntries', ''),
    ('DnsResolverTimeout', 3),
    ('DnsResolverRetries', 1),
    ('PiholeUrl', 'http://192.168.49.80/api'),
    ('PiholeApiKey',''),
    ('DiscoveryReverseDns', '0'),
    ('DiscoveryPiholeDhcp', '0'),
    ('EnableLocalDiscoveryProcess', '0'),
    ('DiscoveryProcessRunInterval', '60'),
    ('DiscoveryNmapOsFingerprint',0),
    ('ReputationUrl','https://iplists.firehol.org/files/firehol_level1.netset'),
    ('ReputationListRemove','192.168.0.0/16,0.0.0.0/8,224.0.0.0/3,169.254.0.0/16'),
    ('ReputationListDetection','0'),
    ('VpnTrafficDetection','0'),
    ('ApprovedVpnServersList',''),
    ('RemoveBroadcastFlows',1),
    ('HighRiskPortDetection','0'),
    ('HighRiskPorts','135,137,138,139,445,25,587,22,23,3389'),
    ('MaxUniqueDestinations','30'),
    ('ManyDestinationsDetection','0'),
    ('MaxPortsPerDestination','15'),
    ('PortScanDetection','0'),
    ('IntegrationFetchInterval',3660),
    ('TorFlowDetection','0'),
    ('TorNodesUrl','https://www.dan.me.uk/torlist/?full'),
    ('HighBandwidthFlowDetection','0'),
    ('MaxPackets',30000),
    ('MaxBytes',3000000),
    ('StorePiHoleDnsQueryHistory','0'),
    ('SendDeviceClassificationsToHomelabApi','0')
    ('CollectorProcessingInterval','60'),
    ('SendErrorsToCloudApi','0'),
    ('RemoveMulticastFlows','1'),
    ('TagEntries', ''),
    ('AlertOnCustomTagList',''),
    ('AlertOnCustomTags','0'),
    ('SendConfigurationToCloudApi','0'),
    ('ApprovedHighRiskDestinations', ''),
    ('MaxMindAPIKey', ''),
    ('ImportServicesList','1'),
    ('TelegramEnabled', '0'),
    ('ImportAsnDatabase', '1'),
    ('PiHoleDnsFetchRecordSize', '10000'),
    ('PiHoleDnsFetchInterval', '3600'),
    ('TrafficStatsPurgeIntervalDays','31'),
    ('SinkHoleDns', '0'),
    ('DnsResponseLookupResolver',''),
    ('PerformDnsResponseLookupsForInvestigations','0')
]