[project]
name = "sando"
dynamic = ["version"]
description = "Network monitoring and analysis tool."
authors = [{name = "Sando", email = "homelabids@gmail.com"}]
license = {text = "GPL-3.0-or-later"}
readme = {file = "README.markdown", content-type = "text/markdown"}
requires-python = ">=3.8"
dependencies = [
  "schedule",
  "requests",
  "bottle",
  "dnspython",
  "python-nmap",
  "psutil",
  "dnslib",
  "waitress",
  "pytz"
]

lint = [
  "flake8",
]

[project.scripts]
collector = "src.processes.collector:main"
processor = "src.processes.processor:main"
api = "src.processes.api:main"
discovery = "src.processes.discovery:main"
watchdog = "src.processes.watchdog:main"
fetch = "src.processes.fetch:main"
sinkholedns = "src.processes.sinkholedns:main"
dhcpserver = "src.processes.dhcpserver:main"
# Add more as needed, ensure each module has a main() function

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
